%
lKeepFrac=false(length(fracEst),nMons,length(planes),nScanSetUps);
lKeepFits=false(nMaxFitSets,nMons,length(planes),nScanSetUps);
%
outNameCompare="2021-09\C270";
%
for iScanSetUps=iMinScanSetUps:iMaxScanSetUps
    switch scanSetUps(iScanSetUps)
        case "2022-03-13\SetMeUp_U1p008ApQUE_C270_primoGiro.m"
            iMon=strcmpi(mons,"CAM");
            iPlane=strcmpi(planes,"HOR");
            lKeepFrac(0.35<=fracEst & fracEst<=0.75,...
                iMon,iPlane,iScanSetUps)=true;
            lKeepFits(1:nFitRanges(:,iScanSetUps)~=1 & 1:nFitRanges(:,iScanSetUps)~=7,...
                iMon,iPlane,iScanSetUps)=true;
            iPlane=strcmpi(planes,"VER");
            lKeepFrac(0.35<=fracEst & fracEst<=0.75,...
                iMon,iPlane,iScanSetUps)=true;
            lKeepFits(1:2,...
                iMon,iPlane,iScanSetUps)=true;
            iMon=strcmpi(mons,"DDS");
            iPlane=strcmpi(planes,"HOR");
            lKeepFrac(0.45<=fracEst & fracEst<=0.75,...
                iMon,iPlane,iScanSetUps)=true;
            lKeepFits(1:nFitRanges(:,iScanSetUps)~=1 & 1:nFitRanges(:,iScanSetUps)~=3 & 1:nFitRanges(:,iScanSetUps)~=7,...
                iMon,iPlane,iScanSetUps)=true;
            iPlane=strcmpi(planes,"VER");
            lKeepFrac(0.25<=fracEst & fracEst<=0.35,...
                iMon,iPlane,iScanSetUps)=true;
            lKeepFits(1,...
                iMon,iPlane,iScanSetUps)=true;
        case "2022-03-13\SetMeUp_U1p014ApQUE_C270_primoGiro.m"
            iMon=strcmpi(mons,"CAM");
            iPlane=strcmpi(planes,"HOR");
            lKeepFrac(0.35<=fracEst & fracEst<=0.65,...
                iMon,iPlane,iScanSetUps)=true;
            lKeepFits(1:nFitRanges(:,iScanSetUps)~=1 & 1:nFitRanges(:,iScanSetUps)~=6 & 1:nFitRanges(:,iScanSetUps)~=7,...
                iMon,iPlane,iScanSetUps)=true;
            iPlane=strcmpi(planes,"VER");
            lKeepFrac(0.45<=fracEst & fracEst<=0.75,...
                iMon,iPlane,iScanSetUps)=true;
            lKeepFits(1:nFitRanges(:,iScanSetUps)~=7,...
                iMon,iPlane,iScanSetUps)=true;
            iMon=strcmpi(mons,"DDS");
            iPlane=strcmpi(planes,"HOR");
            lKeepFrac(0.35<=fracEst & fracEst<=0.65,...
                iMon,iPlane,iScanSetUps)=true;
            lKeepFits(1,...
                iMon,iPlane,iScanSetUps)=true;
            iPlane=strcmpi(planes,"VER");
            lKeepFrac(0.45<=fracEst & fracEst<=0.75,...
                iMon,iPlane,iScanSetUps)=true;
            lKeepFits(1:nFitRanges(:,iScanSetUps)~=7,...
                iMon,iPlane,iScanSetUps)=true;
        case "SetMeUp_U1p018ApQUE_C270_primoGiro"
            iMon=strcmpi(mons,"CAM");
            iPlane=strcmpi(planes,"HOR");
            lKeepFrac(0.35<=fracEst & fracEst<=0.55,...
                iMon,iPlane,iScanSetUps)=true;
            lKeepFits(1:nFitRanges(:,iScanSetUps),...
                iMon,iPlane,iScanSetUps)=true;
            iPlane=strcmpi(planes,"VER");
            lKeepFrac(0.35<=fracEst & fracEst<=0.65,...
                iMon,iPlane,iScanSetUps)=true;
            lKeepFits([1 4 5],...
                iMon,iPlane,iScanSetUps)=true;
            iMon=strcmpi(mons,"DDS");
            iPlane=strcmpi(planes,"HOR");
            lKeepFrac(0.45==fracEst,...
                iMon,iPlane,iScanSetUps)=true;
            lKeepFits(4:5,...
                iMon,iPlane,iScanSetUps)=true;
            iPlane=strcmpi(planes,"VER");
            lKeepFrac(0.35<=fracEst & fracEst<=0.65,...
                iMon,iPlane,iScanSetUps)=true;
            lKeepFits(4:6,...
                iMon,iPlane,iScanSetUps)=true;
        case "2022-03-13\SetMeUp_U2p016ApQUE_C270_primoGiro.m"
            iMon=strcmpi(mons,"CAM");
            iPlane=strcmpi(planes,"HOR");
            lKeepFrac(0.55<=fracEst & fracEst<=0.75,...
                iMon,iPlane,iScanSetUps)=true;
            lKeepFits([3 4 6],...
                iMon,iPlane,iScanSetUps)=true;
            iPlane=strcmpi(planes,"VER");
            lKeepFrac(0.45<=fracEst & fracEst<=0.65,...
                iMon,iPlane,iScanSetUps)=true;
            lKeepFits(1:nFitRanges(:,iScanSetUps),...
                iMon,iPlane,iScanSetUps)=true;
            iMon=strcmpi(mons,"DDS");
            iPlane=strcmpi(planes,"HOR");
            lKeepFrac(0.65<=fracEst & fracEst<=0.75,...
                iMon,iPlane,iScanSetUps)=true;
            lKeepFits(3,...
                iMon,iPlane,iScanSetUps)=true;
            iPlane=strcmpi(planes,"VER");
            lKeepFrac(0.55<=fracEst & fracEst<=0.75,...
                iMon,iPlane,iScanSetUps)=true;
            lKeepFits(1:3,...
                iMon,iPlane,iScanSetUps)=true;
    end
end
